g29_feedback_publisher:
  ros__parameters:
    device_name: "/dev/input/event7"
    loop_period: 0.015
    pub_period: 0.1
    max_torque: 0.35
    min_torque: 0.15
    brake_torque: 0.2
    brake_position: 0.1
    auto_centering_max_torque: 0.6
    auto_centering_max_position: 0.1
    eps: 0.02
    auto_centering: true
